# 🏦💼 DESAFIO FINAL — ANÁLISE DE CORRENTISTAS

Você é analista de dados de um banco e recebeu duas bases:

- 📊 Clientes (`df_clientes`)
- 💳 Transações (`df_transacoes`)

Seu objetivo é limpar, tratar e gerar insights estratégicos.

## 📦 1. Criação dos DataFrames

In [1]:
import pandas as pd
import numpy as np

np.random.seed(42)

# Clientes
df_clientes = pd.DataFrame({
    'id_cliente': np.arange(1, 101),
    'nome': ['Cliente_' + str(i) for i in range(1, 101)],
    'idade': np.random.choice([25, 30, 35, 40, np.nan], 100),
    'cidade': np.random.choice(['RJ', 'SP', 'MG', None], 100),
    'status_conta': np.random.choice(['Ativa', 'Inativa', None], 100),
    'score_credito': np.random.choice([300, 500, 700, 900, np.nan], 100),
    'renda_mensal': np.random.choice([2000, 4000, 6000, 8000, np.nan], 100),
    'segmento': np.random.choice(['Varejo', 'Alta Renda', None], 100)
})

# Inserindo duplicados
df_clientes = pd.concat([df_clientes, df_clientes.iloc[:5]])

# Transações
df_transacoes = pd.DataFrame({
    'id_cliente': np.random.randint(1, 101, 200),
    'valor_transacao': np.random.choice([100, 500, 1000, 2000, np.nan], 200),
    'tipo': np.random.choice(['Crédito', 'Débito'], 200),
    'mes': np.random.choice(['Jan', 'Fev', 'Mar'], 200)
})

df_clientes.head()

,id_cliente,nome,idade,cidade,status_conta,score_credito,renda_mensal,segmento
0,1,Cliente_1,40.0,NaN,NaN,700.0,8000.0,Varejo
1,2,Cliente_2,NaN,MG,Ativa,300.0,4000.0,NaN
2,3,Cliente_3,35.0,RJ,Inativa,700.0,6000.0,Alta Renda
3,4,Cliente_4,NaN,NaN,Ativa,300.0,8000.0,Alta Renda
4,5,Cliente_5,NaN,NaN,Ativa,NaN,NaN,Varejo

## 🎯 MISSÃO DO ALUNO

### 🔎 PARTE 1 — Diagnóstico

**Pergunta 1**  
Quantos valores nulos existem por coluna?

**Pergunta 2**  
Existem registros duplicados?

In [8]:
# Quantos valores nulos existem em cada coluna do DataFrame de clientes?
nulos_por_coluna = df_clientes.isnull().sum()
print(nulos_por_coluna)

# Quantos valores nulos existem em cada coluna do DataFrame de transações?
nulos_por_coluna_transacoes = df_transacoes.isnull().sum()
print(nulos_por_coluna_transacoes)

id_cliente        0
nome              0
idade            22
cidade           27
status_conta     37
score_credito    19
renda_mensal     26
segmento         33
dtype: int64
id_cliente          0
valor_transacao    35
tipo                0
mes                 0
dtype: int64

In [ ]:
# Pergunta 1: Existem registros duplicados no DataFrame de clientes? Se sim, quantos?

duplicados_clientes = df_clientes.duplicated().sum()
print(f"Registros duplicados no DataFrame de clientes: {duplicados_clientes}")

# Pergunta 2: Existem registros duplicados no DataFrame de transações? Se sim, quantos?

duplicados_transacoes = df_transacoes.duplicated().sum()
print(f"Registros duplicados no DataFrame de transações: {duplicados_transacoes}")

Registros duplicados no DataFrame de clientes: 5
Registros duplicados no DataFrame de transações: 6

### 📊 PARTE 2 — Análise exploratória

**Pergunta 3**  
Quantas cidades diferentes existem?

**Pergunta 4**  
Distribuição de status da conta

In [ ]:
# Pergunta 3: Quantas cidades diferentes existem no DataFrame de clientes?
cidades_diferentes = df_clientes['cidade'].nunique()
print(f"Cidades diferentes no DataFrame de clientes: {cidades_diferentes}")

Cidades diferentes no DataFrame de clientes: 3

In [ ]:
# Pergunta 4: Distribuição de status de conta no DataFrame de clientes
distribuicao_status_conta = df_clientes['status_conta'].value_counts()
print("Distribuição de status de conta:")
print(distribuicao_status_conta)

Distribuição de status de conta:
status_conta
Ativa      37
Inativa    31
Name: count, dtype: int64

### 🧹 PARTE 3 — Limpeza de dados

**Pergunta 5**  
Remova duplicados  

**Pergunta 6**  
Preencha valores faltantes:
- idade → mediana  
- renda → média  
- cidade → "Não Informado"  
- status → ffill

In [ ]:
# Pergunta 5: Remova duplicados

df_clientes.drop_duplicates()
df_transacoes.drop_duplicates()

     id_cliente  valor_transacao     tipo  mes
0             7           2000.0   Débito  Mar
1            46            500.0  Crédito  Fev
2            13            500.0   Débito  Fev
3            40            500.0  Crédito  Mar
4            42            500.0  Crédito  Fev
..          ...              ...      ...  ...
195          85           2000.0  Crédito  Jan
196          14           1000.0  Crédito  Jan
197          66           1000.0   Débito  Jan
198          75            100.0  Crédito  Mar
199          51           2000.0   Débito  Fev

[194 rows x 4 columns]

In [29]:
# Pergunta 6: Preencha os valores faltantes na coluna 'idade' do DataFrame de clientes com a mediana das idades.
mediana_idade = df_clientes['idade'].median()
df_clientes['idade'] = df_clientes['idade'].fillna(mediana_idade)

# Preencha os valores faltantes na coluna renda_mensal do DataFrame de clientes com a média das rendas mensais.
media_renda_mensal = df_clientes['renda_mensal'].mean()
df_clientes['renda_mensal'] = df_clientes['renda_mensal'].fillna(media_renda_mensal)

# Preencha os valores faltantes na coluna cidade do DataFrame de clientes com o texto "Não informado".
df_clientes['cidade'] = df_clientes['cidade'].fillna("Não informado")

# Preencha os valores faltantes na coluna status_conta do DataFrame de clientes com o metodo forward fill.
df_clientes['status_conta'] = df_clientes['status_conta'].ffill()

In [30]:
display(df_clientes)

,id_cliente,nome,idade,cidade,status_conta,score_credito,renda_mensal,segmento
0,1,Cliente_1,40.0,Não informado,NaN,700.0,8000.000000,Varejo
1,2,Cliente_2,35.0,MG,Ativa,300.0,4000.000000,NaN
2,3,Cliente_3,35.0,RJ,Inativa,700.0,6000.000000,Alta Renda
3,4,Cliente_4,35.0,Não informado,Ativa,300.0,8000.000000,Alta Renda
4,5,Cliente_5,35.0,Não informado,Ativa,NaN,5316.455696,Varejo
...,...,...,...,...,...,...,...,...
0,1,Cliente_1,40.0,Não informado,Inativa,700.0,8000.000000,Varejo
1,2,Cliente_2,35.0,MG,Ativa,300.0,4000.000000,NaN
2,3,Cliente_3,35.0,RJ,Inativa,700.0,6000.000000,Alta Renda
3,4,Cliente_4,35.0,Não informado,Ativa,300.0,8000.000000,Alta Renda
4,5,Cliente_5,35.0,Não informado,Ativa,NaN,5316.455696,Varejo

### 🔁 PARTE 4 — Regras de negócio

**Pergunta 7**  
Crie a coluna `perfil_risco`:
- "Alto Risco" → score < 500  
- "Médio" → 500–700  
- "Baixo Risco" → > 700

### 🔗 PARTE 5 — JOIN

**Pergunta 8**  
Faça um inner join entre clientes e transações, considere o dataframe sem duplicidade

**Pergunta 9**  
Faça um left join, considere o dataframe sem duplicidade

### 📊 PARTE 6 — Análise estratégica

**Pergunta 10**  
Qual o valor total transacionado por perfil de risco?

**Pergunta 11**  
Qual a média de transação por segmento?  

**Pergunta 12**  
Qual cidade tem maior volume financeiro?  

**Pergunta 13**  
Quantos clientes de alto risco possuem renda alta (> 6000)?  

**Pergunta 14**  
Qual o ticket médio por tipo de transação?  

**Pergunta 15**  
Liste clientes sem transações (apenas no left join)

### ✏️ PARTE 7 — Ajustes pontuais

**Pergunta 16**  
Altere a cidade do primeiro cliente para "ES"

**Pergunta 17**  
Acesse o valor da renda do cliente na linha 10

### 🧠📊 Questão — Integração e Análise de Clientes

Você possui dois DataFrames:

- df_clientes → informações dos correntistas
- df_transacoes → movimentações financeiras

Faça um left join entre df_clientes e df_transacoes utilizando a coluna id_cliente.

Em seguida:

👉 Calcule o valor total transacionado por cliente

👉 Mostre o resultado ordenado do maior para o menor

👉 Importante: clientes sem transações devem aparecer com valor 0

### 🧠📉 Nova questão (focada em saldo negativo)

Após realizar o left join entre clientes e transações:

👉 Considere que:

- valores de transação do tipo "Débito" devem ser negativos
- valores de "Crédito" permanecem positivos

👉 Calcule o saldo final por cliente (soma das transações)

👉 Em seguida:

1. Liste os clientes com saldo negativo
2. Mostre quantos clientes estão nessa situação
3. Calcule o saldo médio desses clientes