Aluno: Gilmar Francisco Kammers Junior

Turma: 1696 CAIXAVERSO - FC3 | Analista Dados - II

Módulo: Técnicas de Programação I PY

# Mini Projeto — Analista de Dados do Banco Fácil 🏦

**Contexto:** Você é analista de dados do Banco Fácil. O banco te enviou uma tabela de transações e uma tabela de cadastro de clientes. Seu trabalho é cruzar essas bases e gerar uma análise rápida.

**Data limite da entrega: ** 10/05/2026

**Entrega: ** Subir na plataforma LMS o arquivo Jupyter Notebook (.ipynb)

---

## Os dados

Crie as duas tabelas abaixo manualmente no início do seu notebook:

```python
import pandas as pd
import numpy as np

# Base de transações
transacoes = pd.DataFrame({
    'id_cliente': [1, 2, 1, 3, 2, 1, 3, 2],
    'tipo':       ['Crédito', 'Débito', 'Débito', 'Crédito', 'Crédito', 'Débito', 'Débito', 'Crédito'],
    'categoria':  ['Salário', 'Alimentação', 'Transporte', 'Salário', 'Lazer', 'Alimentação', 'Transporte', 'Salário'],
    'valor':      [3200.0, 150.0, None, 4500.0, 200.0, 80.0, None, 2800.0],
    'canal':      ['App', 'Agência', 'App', 'Internet Banking', 'App', 'Agência', 'App', 'Internet Banking']
})

# Base de cadastro de clientes
clientes = pd.DataFrame({
    'id_cliente': [1, 2, 3, 4],
    'nome':       ['Ana', 'Bruno', 'Carlos', 'Diana'],
    'estado':     ['SP', 'RJ', 'MG', 'SP'],
    'perfil':     ['Premium', 'Básico', 'Intermediário', 'Básico']
})
```

> **Atenção:** a cliente Diana (id 4) existe no cadastro mas não possui nenhuma transação. Isso é proposital e será explorado nas tarefas.

---

In [43]:
# Criando as tabelas

import pandas as pd
import numpy as np

# Base de transações
transacoes = pd.DataFrame({
    'id_cliente': [1, 2, 1, 3, 2, 1, 3, 2],
    'tipo':       ['Crédito', 'Débito', 'Débito', 'Crédito', 'Crédito', 'Débito', 'Débito', 'Crédito'],
    'categoria':  ['Salário', 'Alimentação', 'Transporte', 'Salário', 'Lazer', 'Alimentação', 'Transporte', 'Salário'],
    'valor':      [3200.0, 150.0, None, 4500.0, 200.0, 80.0, None, 2800.0],
    'canal':      ['App', 'Agência', 'App', 'Internet Banking', 'App', 'Agência', 'App', 'Internet Banking']
})

# Base de cadastro de clientes
clientes = pd.DataFrame({
    'id_cliente': [1, 2, 3, 4],
    'nome':       ['Ana', 'Bruno', 'Carlos', 'Diana'],
    'estado':     ['SP', 'RJ', 'MG', 'SP'],
    'perfil':     ['Premium', 'Básico', 'Intermediário', 'Básico']
})

In [44]:
# Visualizando as tabelas
print("Tabela de Transações:")
display(transacoes)
print("\nTabela de Clientes:")
display(clientes)

Tabela de Transações:

   id_cliente     tipo    categoria   valor             canal
0           1  Crédito      Salário  3200.0               App
1           2   Débito  Alimentação   150.0           Agência
2           1   Débito   Transporte     NaN               App
3           3  Crédito      Salário  4500.0  Internet Banking
4           2  Crédito        Lazer   200.0               App
5           1   Débito  Alimentação    80.0           Agência
6           3   Débito   Transporte     NaN               App
7           2  Crédito      Salário  2800.0  Internet Banking

Tabela de Clientes:

   id_cliente    nome estado         perfil
0           1     Ana     SP        Premium
1           2   Bruno     RJ         Básico
2           3  Carlos     MG  Intermediário
3           4   Diana     SP         Básico

## Tarefas

### Tarefa 1 — Conheça os dados

Use `shape`, `dtypes`, `head()` e `isna().sum()` nas **duas** tabelas separadamente.

- Quantos clientes existem no cadastro? Resposta: 4 Clientes
- Quantas transações existem? Resposta: 8 Transações
- Alguma coluna possui valores nulos? Resposta: Coluna valor na tabela de Transações

---

In [45]:
# Usando `shape`, `dtypes`, `head()` e `isna().sum()` nas **duas** tabelas separadamente.

print("Shape da tabela de clientes:")
print(clientes.shape)

print("\nTipos de dados da tabela de clientes:")
print(clientes.dtypes)

print("\nPrimeiras linhas da tabela de clientes:")
display(clientes.head())

print("\nValores nulos da tabela de clientes:")
print(clientes.isna().sum())

print("\nShape da tabela de transações:")
print(transacoes.shape)

print("\nTipos de dados da tabela de transações:")
print(transacoes.dtypes)

print("\nPrimeiras linhas da tabela de transações:")
display(transacoes.head())

print("\nValores nulos da tabela de transações:")
print(transacoes.isna().sum())

Shape da tabela de clientes:
(4, 4)

Tipos de dados da tabela de clientes:
id_cliente    int64
nome            str
estado          str
perfil          str
dtype: object

Primeiras linhas da tabela de clientes:

   id_cliente    nome estado         perfil
0           1     Ana     SP        Premium
1           2   Bruno     RJ         Básico
2           3  Carlos     MG  Intermediário
3           4   Diana     SP         Básico

Valores nulos da tabela de clientes:
id_cliente    0
nome          0
estado        0
perfil        0
dtype: int64

Shape da tabela de transações:
(8, 5)

Tipos de dados da tabela de transações:
id_cliente      int64
tipo              str
categoria         str
valor         float64
canal             str
dtype: object

Primeiras linhas da tabela de transações:

   id_cliente     tipo    categoria   valor             canal
0           1  Crédito      Salário  3200.0               App
1           2   Débito  Alimentação   150.0           Agência
2           1   Débito   Transporte     NaN               App
3           3  Crédito      Salário  4500.0  Internet Banking
4           2  Crédito        Lazer   200.0               App

Valores nulos da tabela de transações:
id_cliente    0
tipo          0
categoria     0
valor         2
canal         0
dtype: int64


### Tarefa 2 — Limpeza

Preencha os valores nulos da coluna `valor` com a **mediana geral** da coluna.  
Use `fillna()`.

Confirme que não existem mais nulos com `isna().sum()`.

---

In [46]:
# Preenchendo valores nulos com a mediana geral da coluna

mediana_valor = transacoes['valor'].median()
transacoes['valor'] = transacoes['valor'].fillna(mediana_valor)
print("\nValores nulos após preenchimento na tabela de transações:")

# Confirmando que não há mais valores nulos
print(transacoes.isna().sum())

Valores nulos após preenchimento na tabela de transações:
id_cliente    0
tipo          0
categoria     0
valor         0
canal         0
dtype: int64


### Tarefa 3 — Cálculos com NumPy

Com os valores da coluna `valor` (já limpa), crie um array NumPy e calcule:

- Soma total das transações
- Valor médio
- Maior valor
- Menor valor

In [47]:
# Criando um array Numpy a partir da coluna 'valor' e calculando soma total, a média, maior valor e menor valor.
valores_array = transacoes['valor']
soma_total = np.sum(valores_array)
media_valores = np.mean(valores_array)
maior_valor = np.max(valores_array)
menor_valor = np.min(valores_array)

print(f"\nSoma total dos valores: {soma_total}")
print(f"Média dos valores: {media_valores}")
print(f"Maior valor: {maior_valor}")
print(f"Menor valor: {menor_valor}")

Soma total dos valores: 13930.0
Média dos valores: 1741.25
Maior valor: 4500.0
Menor valor: 80.0


---

### Tarefa 4 — Join entre as bases

Faça um `merge` entre `transacoes` e `clientes` usando `id_cliente` como chave.

- Faça um **inner join** e salve em `df_inner`
- Faça um **left join** partindo de `clientes` e salve em `df_left`
- Compare o `shape` dos dois resultados

Em uma célula Markdown, explique com suas palavras: **por que os shapes são diferentes?**

---

In [48]:
# Merge das tabelas de transações e clientes
# Inner join 
df_inner = pd.merge(transacoes, clientes, on='id_cliente', how='inner')
print("\nTabela com inner join:")
display(df_inner)

# Left join com clientes à esquerda
df_left = pd.merge(clientes, transacoes, on='id_cliente', how='left')
print("\nTabela com left join:")
display(df_left)

# Comparando o shape dos dois resultados:
print("\nShape do DataFrame com inner join:", df_inner.shape)
print("Shape do DataFrame com left join:", df_left.shape)

Tabela com inner join:

,id_cliente,tipo,categoria,valor,canal,nome,estado,perfil
0,1,Crédito,Salário,3200.0,App,Ana,SP,Premium
1,2,Débito,Alimentação,150.0,Agência,Bruno,RJ,Básico
2,1,Débito,Transporte,1500.0,App,Ana,SP,Premium
3,3,Crédito,Salário,4500.0,Internet Banking,Carlos,MG,Intermediário
4,2,Crédito,Lazer,200.0,App,Bruno,RJ,Básico
5,1,Débito,Alimentação,80.0,Agência,Ana,SP,Premium
6,3,Débito,Transporte,1500.0,App,Carlos,MG,Intermediário
7,2,Crédito,Salário,2800.0,Internet Banking,Bruno,RJ,Básico

Tabela com left join:

,id_cliente,nome,estado,perfil,tipo,categoria,valor,canal
0,1,Ana,SP,Premium,Crédito,Salário,3200.0,App
1,1,Ana,SP,Premium,Débito,Transporte,1500.0,App
2,1,Ana,SP,Premium,Débito,Alimentação,80.0,Agência
3,2,Bruno,RJ,Básico,Débito,Alimentação,150.0,Agência
4,2,Bruno,RJ,Básico,Crédito,Lazer,200.0,App
5,2,Bruno,RJ,Básico,Crédito,Salário,2800.0,Internet Banking
6,3,Carlos,MG,Intermediário,Crédito,Salário,4500.0,Internet Banking
7,3,Carlos,MG,Intermediário,Débito,Transporte,1500.0,App
8,4,Diana,SP,Básico,NaN,NaN,NaN,NaN

Shape do DataFrame com inner join: (8, 8)
Shape do DataFrame com left join: (9, 8)

Por que os shapes são diferentes?
Resposta: O inner join retorna apenas as linhas que têm correspondência em ambas as tabelas, enquanto o left join retorna todas as linhas da tabela da esquerda (clientes) e as correspondências da tabela da direita (transações),preenchendo com NaN onde não há correspondência.


### Tarefa 5 — Investigando o left join

No `df_left`, use `loc` para filtrar apenas as linhas onde `valor` está nulo.

- Qual cliente consta no cadastro mas nunca realizou uma transação?

---

In [49]:
linhas_nulas = df_left.loc[df_left['valor'].isna()]
print("\nQual cliente consta no cadastro mas nunca realizou uma transação?:")
display(linhas_nulas)

Qual cliente consta no cadastro mas nunca realizou uma transação?:

   id_cliente   nome estado  perfil tipo categoria  valor canal
8           4  Diana     SP  Básico  NaN       NaN    NaN   NaN


### Tarefa 6 — Análise por perfil

Usando o `df_inner`, aplique `groupby` na coluna `perfil` e calcule a **soma** e a **média** dos valores por perfil de cliente.

- Qual perfil teve o maior valor médio por transação?

In [50]:
# Usando o `df_inner`, aplique `groupby` na coluna `perfil` e calcule a **soma** e a **média** dos valores por perfil de cliente.

grouped = df_inner.groupby('perfil')['valor'].agg(['sum', 'mean'])
print("\nSoma e média dos valores por perfil de cliente:")
display(grouped)

# Qual perfil de cliente tem a maior média de valor transacionado?
# Resposta: O perfil Intermediario teve o maior valor medio por transação

Soma e média dos valores por perfil de cliente:

                  sum         mean
perfil
Básico         3150.0  1050.000000
Intermediário  6000.0  3000.000000
Premium        4780.0  1593.333333


---

### Tarefa 7 — Salvar o resultado

Salve o `df_inner` em um arquivo chamado `base_combinada.csv`.  
Use `to_csv(index=False)`.

Leia o arquivo salvo com `pd.read_csv()` para confirmar que foi gravado corretamente.

In [51]:
# Salvando o df_inner em um arquivo CSV
df_inner.to_csv('base_combinada.csv', index=False)

# Lendo o arquivo CSV
df_combinada = pd.read_csv('base_combinada.csv')
print("\nDataFrame lido do arquivo CSV:")
display(df_combinada)

DataFrame lido do arquivo CSV:

,id_cliente,tipo,categoria,valor,canal,nome,estado,perfil
0,1,Crédito,Salário,3200.0,App,Ana,SP,Premium
1,2,Débito,Alimentação,150.0,Agência,Bruno,RJ,Básico
2,1,Débito,Transporte,1500.0,App,Ana,SP,Premium
3,3,Crédito,Salário,4500.0,Internet Banking,Carlos,MG,Intermediário
4,2,Crédito,Lazer,200.0,App,Bruno,RJ,Básico
5,1,Débito,Alimentação,80.0,Agência,Ana,SP,Premium
6,3,Débito,Transporte,1500.0,App,Carlos,MG,Intermediário
7,2,Crédito,Salário,2800.0,Internet Banking,Bruno,RJ,Básico



---

## Critérios de entrega

| Item | Descrição |
|---|---|
| Execução | Notebook roda do início ao fim sem erros |
| Comentários | Cada célula possui um comentário explicando o que está sendo feito |
| Markdown | Tarefa 4 respondida em célula Markdown com explicação própria |

---

*Banco Fácil — Programa de Dados*